
project_id = "qkhaommjlbxnlvmzgugd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[functions]
[functions.create-checkout]
verify_jwt = true
[functions.customer-portal]
verify_jwt = true

[storage]
enabled = true
