version: '3.8'

services:
  # Development service with hot reloading
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: npm run dev
    
  # Production build
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:80"
    # If you want to add environment variables
    # environment:
    #   - VITE_API_URL=your_api_url 