
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkhaommjlbxnlvmzgugd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFraGFvbW1qbGJ4bmx2bXpndWdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NzA0MzMsImV4cCI6MjA2MjU0NjQzM30.L8w2sWU8VWeMoXvmGh82vlfKnSqYwanSa_pu0xsocaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
